# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:
  datasource:
    jdbcUrl: DB_MYSQL_DESAENV04_DATABASESE_DATABASESE_ENDPOINT
    username: databasese_WPROD
    db: databasese
    password: DB_MYSQL_DESAENV04_DATABASESE_DATABASESE_WPROD
    driverClassName: com.mysql.cj.jdbc.Driver
    auto-commit: true
    hikari:
      # https://bit.ly/3eGDwz2
      maximum-pool-size: 30
      minimum-idle: 15
      connection-timeout: 30000
      idleTimeout: 600000
      readOnly: false
      max-life-time: 400000
      leak-detection-threshold: 30000
      connection-init-sql: SELECT 1
      auto-commit: false
      # https://bit.ly/2AYCgZQ
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  batch:
    initialize-schema: never