USE MOVIES_DB;

--EJERCICIO 1

SELECT 
    S.TITLE,
    G.NAME
FROM SERIES S
INNER JOIN GENRES G ON S.GENRE_ID = G.ID;


--EJERCICIO 2

SELECT 
    TITLE,
    FIRST_NAME 'ACTOR NAME',
    LAST_NAME 'ACTOR LAST NAME'
FROM ACTOR_EPISODE AE 
INNER JOIN EPISODES E ON AE.EPISODE_ID = E.ID
INNER JOIN ACTORS A ON AE.ACTOR_ID = A.ID;


--EJERCICIO 3

SELECT 
    SE.TITLE, 
    COUNT(*) 'TOTAL TEMP'
FROM SERIES SE
INNER JOIN SEASONS S ON S.SERIE_ID = SE.ID
GROUP BY S.SERIE_ID;


--EJERCICIO 4

SELECT 
    G.NAME,
    COUNT(*) TOTAL
FROM GENRES G
INNER JOIN MOVIES M ON M.GENRE_ID = G.ID
GROUP BY M.GENRE_ID
HAVING TOTAL > 3;


--EJERCICIO 5

SELECT 
    A.FIRST_NAME,
    A.LAST_NAME
FROM ACTOR_MOVIE AM
INNER JOIN ACTORS A ON AM.ACTOR_ID = A.ID
INNER JOIN MOVIES M ON AM.MOVIE_ID = M.ID
WHERE M.TITLE LIKE 'La Guerra de las galaxias%'
GROUP BY A.FIRST_NAME, A.LAST_NAME;


--EJERCICIO 6

SELECT 
    A.FIRST_NAME,
    A.LAST_NAME,
    COUNT(M.GENRE_ID) TOTAL
FROM ACTORS A
INNER JOIN ACTOR_MOVIE AM ON AM.ACTOR_ID = A.ID
INNER JOIN MOVIES M ON AM.MOVIE_ID = M.ID
GROUP BY A.FIRST_NAME, A.LAST_NAME 
ORDER BY TOTAL DESC; 